services:
  - type: web
    name: discord-bot-treomay
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DISCORD_TOKEN
        sync: false
